project:
  type: website
  output-dir: docs

website:
  description: "I'm Tom Mills, a sociologist in the UK. This is my personal website."
  site-url: https://github.com/tamills1981/society-from-the-top-down
  title: "Society From the Top Down"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tamills1981
      - icon: bluesky
        href: https://bsky.app/profile/tommills.bsky.social
      - icon: twitter-x
        href: https://x.com/ta_mills
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css


