project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Society From the Top Down"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tamills1981
      - icon: bluesky
        href: https://bsky.app/profile/tommills.bsky.social
      - icon: twitter-x
        href: https://x.com/ta_mills
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



